version: 2

sources:
    - name: fruit_export
      description: This is a replica of the Postgres database used by our app
      database: trepz-gcp-data-eng
      schema: fruit_export
      tables:
          - name: raw_sars_export_data
            description: Testing
