version: 2

sources:
    - name: fruit_export
      description: Fruit export project datasets
      database: trepz-gcp-data-eng
      schema: fruit_export
      tables:
          - name: raw_sars_export_data
            description: raw SARS tariff data
          - name: lkp_hs_code_data
            description: HS codes and descriptions derived from SARS Tarriff Book
